In [2]:
import numpy as np # Numerical python

x = np.array([(0.8,0.2),(0.5,0.5),(0.42,0.58)])
np.argmax(x)
y = np.array([1,2,3,4,5])
y


array([1, 2, 3, 4, 5])

In [7]:
x = np.array([[1,2],[3,4],[5,6]])
print(x.shape)
x

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
p = np.full((3,4),8)
p

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [3]:
d = np.ones((4,4))#np.zeros()
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.arange(0,5)
np.arange(0,27,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [4]:
y = np.ones((1,10))
y/5

array([[0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]])

In [7]:
x = d.flatten();d.shape,x.shape

((4, 4), (16,))

In [12]:
# expand
array = np.ones((4,));print(array)
expand = array[np.newaxis,:];print(array.shape,expand.shape)
expand 

[1. 1. 1. 1.]
(4,) (1, 4)


array([[1., 1., 1., 1.]])

In [14]:
array = np.array([[23,17,45],[18,97,100]])
array

array([[ 23,  17,  45],
       [ 18,  97, 100]])

In [16]:
array[array<20]

array([17, 18])

In [20]:
# stack the numopy

first = np.full((2,12),2);print(first.shape)
second = np.full((2,17),2);print(second.shape)
print(first)
print(second)
y = np.hstack((first,second));y.shape

(2, 12)
(2, 17)
[[2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2]]
[[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]]


(2, 29)